### ISSUE TITLE
.gmbh tld and 

### ISSUE THREAD

**Issue by DaH0ff** [microsoft/idfix#10]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of IdFix you are using: [ 2.1.2.0 ]

### Expected / Desired Behavior / Question
Please add .gmbh to the list of tld's

**Comment by patrick-rodgers** [comment]
Will be sure to add this to the next release, thanks!

**Comment by patrick-rodgers** [comment]
Closing this as the .gmbh domain is now in the list. Thanks for the suggestion, will go out in the next release, which I am going to aim for today (4/6/2020). Just need to get the PR merged and then publish the files.
