### ISSUE TITLE
False warnings about X400/X500 Addresses in Proxy Addresses

### ISSUE THREAD

**Issue by FrankCarius** [microsoft/idfix#12]
Nearly all Exchange OnPremises topologies are still using X400 Addresses (from old Exchange 5.x setups many years ago). They never enen think about removing them (not being aware that they are there). 
We also have X500 addresses which are for "Cross Forest Migrations" and they contain the "LegacyExchangeDN" to allow delivery to migrated mailboxes. 

I see a  lot of errore about characters in ProxyAddresses in combination with X400/X500. The reason are "Spaces" in the X400/X500 Address. I tried to find a description about valid characters for these types but was not successfull. But all my addresses were created by the Exchange ProxyDLLs and i'm sure they to it right. so i assume, that <space> is a valid character for these types.

**Comment by PaulieShore** [comment]
We are seeing the same issue. X400 ProxyAddresses containing spaces are throwing a "character" error. These were all created by Exchange. They don't seem to have any impact to our AAD Synchronization though - it's successful.

**Comment by patrick-rodgers** [comment]
Please see [the update on](https://github.com/microsoft/idfix/issues/14) our efforts to refactor the code.

**Comment by patrick-rodgers** [comment]
I updated the character checks for proxy address to allow spaces, will go out in the next release. Thanks for letting us know about this opportunity to improve.

**Comment by patrick-rodgers** [comment]
On this one - doing some research and seeing a (,) char in some x400/500 addresses, which will also be flagged as invalid.

We could ignore and not check any addresses starting with an "x" or make it more specific to the x.400/x.500 and ignore those? Thoughts from folks on the best way to handle these "special" addresses?

**Comment by patrick-rodgers** [comment]
I found the spec for the x500 & x400 addresses and each now have their own regex. If further issues are found will be a quick and easy update to adjust for these.

**Comment by patrick-rodgers** [comment]
This will go out in the 2.2.0.0 release, closing the issues as fixed. Thanks!
