### ISSUE TITLE
Code Refactor Update

### ISSUE THREAD

**Issue by patrick-rodgers** [microsoft/idfix#14]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [ latest        ]

We are seeing an uptick in usage of IdFix, which is great and we are excited for all the feedback. In reviewing the issues and looking over the code we decided to take the time to do a larger refactor to make it easier to maintain, add comments, and decouple the logic which is currently contained almost exclusively within in "Form1.cs".

This means that fixing the open issues and publishing a new release will take a bit longer than we planned, but future updates should be quicker.

We have no plans to make any changes to the user experience of the tool and do not plan any UI changes with the code refactor. When done we aim to deliver the same tool with hopefully some small performance improvements and fixes to the open issues.

### How you can help

If you are interested in helping test beta versions of the refactored code to compare to the existing tool we would appreciate it. While we do our best to test things, nothing can duplicate the nature of different production environments across the world. More testing is always better. If you want to help please comment below and once we are ready we'll update with how to test beta versions. Thanks!

**Comment by disiku** [comment]
Interested in testing tld and X400 fix.

**Comment by pergranath** [comment]
Also interested in testing X400 whitespace error, and all TLD to work as topleveldomain.

**Comment by patrick-rodgers** [comment]
@disiku and @pergranath - can you drop me an email so I can share a link to try a beta?
