### ISSUE TITLE
The server does not support the control. The control is critical.

### ISSUE THREAD

**Issue by arunanand999** [microsoft/idfix#17]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://microsoft.github.io/idfix/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

> If you are reporting a security related issue, instead of submitting it here, please email secure@microsoft.com to ensure it is properly handled to resolution.

### Category
- [ ] Question

### Version
Please specify what version of IdFix you are using: [  2.2.0.0]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*
I am using the version 2.2.0.0

### Expected / Desired Behavior / Question
I am expecting the output. But the tool is crashing with an error

### Observed Behavior
The tool is crashing with an error
"The server does not support the control. The control is critical."

### Steps to Reproduce
I can reproduce the issue gain. I am running on 2012 R2 server.

**Comment by patrick-rodgers** [comment]
That's one we have never seen before. Can you provide any additional details around your version of AD or anything that might affect queries (AD settings, version)? A quick search for that error mentions paging a lot, which we use. It might also be related to the amount of information coming back is too high. But not sure which makes any help you can give us in tracking it down so we can repro it and fix it would be appreciated. Until we can see it fail we would just be guessing as to what happening in your case.

**Comment by arunanand999** [comment]
AD Version: Windows server 2012 R2. It has 4 child domains. 
The information return back or processing should be huge since the amount of data in AD is huge.
Let me know if you need more information.

**Comment by DavidHughes1978** [comment]
I'm seeing the same issues running it on server 2016

**Comment by patrick-rodgers** [comment]
Closing this and merging discussion with #20 as they are all likely related based on reported symptoms. Want to join all threads for visibility.

**Comment by bryan-phillips** [comment]
Some users get this error message when connecting to LDAP using Negotiate auth type.  Using Basic or NTLM auth type could resolve the issue.

**Comment by cooldog77** [comment]
I just got the same error on 2.6.0.2 from Server 2019 on domain and forest function levels 2012.
Thoughts?
