### ISSUE TITLE
Not able to install IdFix tool on windows server 2016

### ISSUE THREAD

**Issue by pedro-roeseler** [microsoft/idfix#20]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
 2.2.00 

### Expected / Desired Behavior / Question

I'm having some customers complaining about not being able to lunch IdFix tool from the setup file. I am having the same issue on a windows 2016 server but on windows 10 it works without any issues... Version 2.2.00
Error message:
Launching Application.URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://raw.githubusercontent.com/Microsoft/idfix/master/publish/IdFix.application'.
I am able to open the URL manually in the browser.

![idfix_error](https://user-images.githubusercontent.com/62067072/86914277-ee9e9400-c117-11ea-9cf2-3e8dcd611a2f.png)

Any idea what might be causing this?
Thanks in advance!
Cheers,
Pedro

**Comment by patrick-rodgers** [comment]
Thanks for reaching out with your question. Did you review the indicated log file and were there any hints as to what might be causing the problem?

**Comment by pedro-roeseler** [comment]
Hi Patrick.
Thanks for the feedback.
Yes, the log only had this information:

The following properties have been set:
```
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 3 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 394802
Setting value '394802 {int}' for property 'DotNet45Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet45Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)':
Property: [DotNet45Full_OSIntegrated] = 1 {int}
Property: [DotNet45Full_Release] = 394802 {int}
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet45Full_Release' and value '379893': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet45Full_Release' and value '379893': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.5.2 (x86 and x64)' RunCheck result: **No Install Needed**
Launching Application.
**URLDownloadToCacheFil**e failed with HRESULT '-2146697208'
**Error: An error occurred trying to download 'https://raw.githubusercontent.com/Microsoft/idfix/master/publish/IdFix.application'.**
```

Cheers,
Pedro

**Comment by kevinblumenfeld** [comment]
I had the exact same issue on 2016.  Wondering if this is not a TLS versioning issue.

**Comment by pedro-roeseler** [comment]
Just to check if you have any feedback on this.

**Comment by jwilkes260** [comment]
I installed IdFix on a Windows 2016 VM and it worked.

```
PS C:\Users\jw> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393
```

The error, `-2146697208`, indicates that there was an issue downloading the file (`INET_E_DOWNLOAD_FAILURE`).

**Comment by shockelite** [comment]
Same error on Window Server 2019 (17763.1158).
![2020-08-06 14_14_19-Window](https://user-images.githubusercontent.com/8532382/89583498-4bf93400-d7ef-11ea-956c-ca45cfb9d80d.png)

**Comment by jwilkes260** [comment]
This might be a networking issue. Have you tried this from another network or location?

**Comment by kevinblumenfeld** [comment]
I have been using IDFix for years without issue. This version is the first that is causing me issues.  I am having to install a version that is four years old.  It is clear there is something going on with this packaged click to run version.  Like the PowerShell Gallery that began enforcing TLS1.2 I am wondering if this is not a similar issue?

**Comment by patrick-rodgers** [comment]
Going to tag in #17 and #22 into this issue as they are all install related to join the conversation. While looking at the August release we were still unable to duplicate these install issues. We just released 2.3.0.0 - please give that a try and see if somehow it fixes the install problem - though I am not aware of why it would. We did test out various TLS versions and couldn't find a way to duplicate the reported behavior. Since multiple people report it something is not working, we just can't yet figure out what.

**Comment by jake-ct** [comment]
Getting the same error on 2012r2, trying the latest 2.3.0.0. Similar [log file](https://github.com/microsoft/idfix/files/5098965/install.log) and exact same HRESULT.

I did find a workaround that let me install & run IDFix, at least in my specific scenario:

1. Set Internet Explorer as default browser
2. Reset IE security settings: Internet Options>Security tab>Reset All Zones to Default Level
3. Open the [faulting URL](https://raw.githubusercontent.com/Microsoft/idfix/master/publish/IdFix.application) in IE and leave it open
4. Run the clickonce installer

**Comment by Tripwyr** [comment]
This issue occurs for me when SSL caching is disabled. The following registry change fixes the issue, it can be changed back immediately if necessary:

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
"DisableCachingOfSSLPages"=dword:00000000

**Comment by spchester** [comment]
Jake's fix didn't work for me on a brand new server 2019 install (converted from eval), but the registry change did the trick.

**Comment by samody** [comment]
__**The registry change worked here also on Server 2016**__ 

> This issue occurs for me when SSL caching is disabled. The following registry change fixes the issue, it can be changed back immediately after installation if necessary:
> 
> [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
> "DisableCachingOfSSLPages"=dword:00000000

**Comment by andygen21** [comment]
i encountered this issue on an Windows 2019 server standard. The registry fix posted by Tripwyr above worked.

**Comment by myitguycorp** [comment]
> This issue occurs for me when SSL caching is disabled. The following registry change fixes the issue, it can be changed back immediately after installation if necessary:
> 
> [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
> "DisableCachingOfSSLPages"=dword:00000000

The registry change also worked on Server 2012R2

**Comment by zRISC** [comment]
that registry change worked on Windows Server 2019 as well

**Comment by Bryand13** [comment]
If everyone is wondering. Also, workaround provided by Trypwyr, is working on Windows Server 2022

**Comment by elray** [comment]
worked form me on  Windows Server 2019 Datacenter.

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
"DisableCachingOfSSLPages"=dword:00000000

**Comment by abfhik** [comment]
ERROR DETAILS
	Following errors were detected during this operation.
	* [11/27/2022 10:59:11 AM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from https://raw.githubusercontent.com/Microsoft/idfix/master/publish/IdFix.application: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestSemanticValidation)
		- Deployment manifest is not semantically valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSemanticsForDeploymentRole()
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (InvalidManifest)
		- Deployment manifest identity contains missing or unsupported processor architecture.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSemanticsForDeploymentRole()
[LG6GGZJV.log](https://github.com/microsoft/idfix/files/10097493/LG6GGZJV.log)

**Comment by cb3inco** [comment]
MSI installer worked for me on Windows 2022 Server machine.

**Comment by PeterCheungHK** [comment]
some error because Microsoft disabled SSL caching 

`Set-ItemProperty -Path "HKCU:Software\Microsoft\Windows\CurrentVersion\Internet Settings" -Name "DisableCachingOfSSLPages" -Value 0`

**Comment by sy5tem** [comment]
server manager "ie enchanced security: off worked for me

**Comment by MWGMorningwood** [comment]
> server manager "ie enchanced security: off worked for me

This was it for me.
Didn't even bother trying the RegKey as this seemed more basic than the symptoms.
Flipping IE ES off worked perfectly on '22.

**Comment by chocoken** [comment]
> worked form me on Windows Server 2019 Datacenter.
> 
> [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings] "DisableCachingOfSSLPages"=dword:00000000

Worked from me on Windows 2019 Standard as well

**Comment by mcbsys** [comment]
Same issue with Server 2025 until I disabled IE Extended Security. 

If this has been a known bug for five years, why not update setup.exe at least with a meaningful message, or better with an actual fix that allows downloading the file? This is supposed to make AD migration _easier_, not throw up roadblocks.
