### ISSUE TITLE
Duplicate Proxy Addresses not detected by tool

### ISSUE THREAD

**Issue by Don-Fuego** [microsoft/idfix#21]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://microsoft.github.io/idfix/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

> If you are reporting a security related issue, instead of submitting it here, please email secure@microsoft.com to ensure it is properly handled to resolution.

### Category
- [ ] Enhancement
- [ X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [ 2.2.0.0     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*
IDFix to report duplicate Proxy Addresses found

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a suggestion or asking a question delete this section.*
None found, but should report duplicate proxy address

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

Add 2 users with the same Proxy Address
![image](https://user-images.githubusercontent.com/41492230/88095044-578b0080-cb49-11ea-91af-acc58ee849ec.png)

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Under settings if you adjust the port to 389 you should see the duplicates. Sometimes not all the information is returned by the default port depending on your AD settings. You can [read more in this thread](https://social.technet.microsoft.com/Forums/Lync/en-US/e52b9154-b93a-4a3b-b6f2-0285f932da14/389-and-3268-port-difference). Thanks!
