### ISSUE TITLE
IdFix install error

### ISSUE THREAD

**Issue by RandyInHawaii** [microsoft/idfix#22]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://microsoft.github.io/idfix/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

> If you are reporting a security related issue, instead of submitting it here, please email secure@microsoft.com to ensure it is properly handled to resolution.

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [   2.2.0.0      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior

Install fails, with the following error:
An error occurred trying to download 'https://raw.githubusercontent.com/Microsoft/idfix/master/publish/IdFix.application'.

See the setup log file located at 'C:\Users\scg\AppData\Local\Temp\2\VSD3C4E.tmp\install.log' for more information.
The log file contains the following:
The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 3 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 6.3.0 {version}
Running checks for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 528049
Setting value '528049 {int}' for property 'DotNet45Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet45Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)':
Property: [DotNet45Full_OSIntegrated] = 1 {int}
Property: [DotNet45Full_Release] = 528049 {int}
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet45Full_Release' and value '379893': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet45Full_Release' and value '379893': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.5.2 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://raw.githubusercontent.com/Microsoft/idfix/master/publish/IdFix.application'.

### Steps to Reproduce

Logged in as the domain admin, tried logging in as an alternate domain admin, also tried downloading/installing on a system other than the two DC's, none of it worked.  (Server 2012r2 or later in all cases, latest .Net installed)

Thank you for your feedback!

**Comment by RandyInHawaii** [comment]
Additional Details:
The error occurs once the initial setup.exe is downloaded and run by clicking on the "launch" link.  The setup.exe is downloaded successfully, it runs but then errors out.  I also tried running it from the download as administrator, and the URL it spits out that it cannot reach, can be pasted into Chrome and used successfully there - so the URL is not being blocked on the target system.

**Comment by patrick-rodgers** [comment]
Closing this and merging discussion with #20 as they are all likely related based on reported symptoms. Want to join all threads for visibility.

**Comment by expertadmins** [comment]
The solution is to temporary disable DisableCachingOfSSLPages

This solution worked for me.
https://woshub.com/idfix-prepare-on-prem-active-directory-sync-azure/
