### ISSUE TITLE
Invalid IdFix Download URL provided by Office 365 Admin Center

### ISSUE THREAD

**Issue by Marcoevich** [microsoft/idfix#23]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [   none     ]

### Question / Observed Behavior
This page in the Microsoft 365 Admin Center provides an invalid url to download the IdFix program: https://admin.microsoft.com/AdminPortal/Home#/dirsyncmanagement

The provided link is this, which leads to a non-existing page: https://go.microsoft.com/fwlink/?linkid=867219

### Steps to Reproduce
Visit this page in a Microsoft 365 tenant which has dir-sync issues: https://admin.microsoft.com/AdminPortal/Home#/dirsyncmanagement

### Screenshots:
![afbeelding](https://user-images.githubusercontent.com/1243033/89417193-a67e8b80-d72e-11ea-99a8-3b2044fc8808.png)

**Comment by patrick-rodgers** [comment]
Thanks for letting us know we are working through making updates to the admin center.
