### ISSUE TITLE
Search Base not working

### ISSUE THREAD

**Issue by stephenion** [microsoft/idfix#25]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [  2.2.0.0       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Able to search a specific OU using the search base option in the connection screen.

### Observed Behavior
When entering a value in the search base, tick the box to enable the search base text box, when entering a value, and clicking OK, i then go back in and edit the connection,, the search base box is ticked, but the value entered is blank, so the search base appears to have no effect when doing a search. 

### Steps to Reproduce
Open IDfix, click the Cog to configure connection, enter value in search base, click OK.  Click cog again, an value is blank.

Thanks,
Steve

**Comment by patrick-rodgers** [comment]
For this one search base was applied correctly, but there was a UI bug. If you checked the box and entered a base it was applied. If you returned to the settings and unchecked the box it was removed. If you _then_ returned to settings the checkbox was still checked but the box was empty. We cleaned up this UI behavior. Thanks for reporting the bug!

**Comment by patrick-rodgers** [comment]
Just released 2.3.0.0 including a fix for this issue. Please try out the latest version and you should no longer see this issue. Thank you for your patience and for reporting the issue allowing us to get it fixed. Thank you!
