### ISSUE TITLE
Not Installing.  

### ISSUE THREAD

**Issue by normandk** [microsoft/idfix#35]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://microsoft.github.io/idfix/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

> If you are reporting a security related issue, instead of submitting it here, please email secure@microsoft.com to ensure it is properly handled to resolution.

### Category
- [ ] Enhancement
- [X ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [    2.3.0.0     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*Running setup creates a Start menu Item for iDfix that you can then click to launch.

Also, Where are the transaction Log Files?*

### Observed Behavior
*after running Setup, the shortcuts are in teh start menu but they lead to nothing and do not launch iDfix.  If I run the setup.exe it launches iDfix

suggestion or asking a question delete this section.*

### Steps to Reproduce
*Run Setup and try to Launch from Start menu on Server 2016 Data Center edition and nothing happens.*

Thank you for your feedback!

**Comment by bryan-phillips-ms** [comment]
An MSI is available for install to those that cannot run the ClickOnce application:  https://github.com/microsoft/idfix/tree/master/MSIs
