### ISSUE TITLE
IDFIX not installing and or working

### ISSUE THREAD

**Issue by peterjoinobits** [microsoft/idfix#36]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://microsoft.github.io/idfix/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

> If you are reporting a security related issue, instead of submitting it here, please email secure@microsoft.com to ensure it is properly handled to resolution.

### Category
- [ ] Enhancement
- [* ] Bug
- [* ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [ 2.3.0.0        ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
Version 2.3.0.0. will not operate correctly in my customer's environment. If I try and install it, either by clicking on the ClicktoRun link, or downloading whilst I'm connected to their network I get what appears to be a TLS/certificate revocation failure. 

If I install it, whilst not connected ,and then connect to their network and run it I get the following experience:

1.) The software launches
2.) It detects my logged in forest name
3.) When I click query it appears to make a connection but it just sits there with the "Starting Query" indicator in the lower left corner of the Window and never gets any further. 

There's is nothing of any value in the logs of the application but I will try and follow up with some logs tomorrow...

**Comment by peterjoinobits** [comment]
I've managed to work around this, issue appears to be related to installer permissions. However this version of IDFIX is not recognizing ,africa as a valid top level domain name causing false positives. Is this list stored within a configuration file in the application anywhere or would a file need to be updated  in the Github repository? I noticed in the build file download there is a file called domains.txt and I've verified that .africa is not listed there...

**Comment by peterjoinobits** [comment]
I can confirm that the .africa entry does not appear to be in the domains.txt file in the src folder for vers 2.3.0.0 that I found at this location: https://github.com/microsoft/idfix/blob/master/src/domains.txt Quire a few companies in Africa are starting to use this domain name and I think the IDFIX application needs to be fixed to reflect that .africa is a valid TLD

**Comment by peterjoinobits** [comment]
As a further update I ran version 1.11 of IDFIX against the same environment and got different results. In this instance the duplicate entries are actually displayed in the output file. I'm not sure if I've discovered a bug or it has to do with how IDFIX is querying AD but there is absolutely a difference between the two sets of output...

**Comment by bryan-phillips-ms** [comment]
An MSI is available for install to those that cannot run the ClickOnce application:  https://github.com/microsoft/idfix/tree/master/MSIs
