### ISSUE TITLE
ToplevelDomain Error for .Swiss Internet Domain

### ISSUE THREAD

**Issue by weyCC81** [microsoft/idfix#38]
**Like: https://github.com/microsoft/idfix/issues/5**

### Category
- [X ] Enhancement

### Version
IdFix 2.3.00

### Expected / Desired Behavior / Question
I would expect to no TopLevelDomain Error for .Swiss TLD

### Observed Behavior
IdFix reports a TopLevelDomain Error for .Swiss which is a routable TLD.

Thanks
Stefan

**Comment by weyCC81** [comment]
@bryan-phillips any updates on this?

**Comment by bryan-phillips-ms** [comment]
This is now fixed in release 2.4.0.0.
