### ISSUE TITLE
Dedicated tenant, error on the targetAddress attribute at Blank

### ISSUE THREAD

**Issue by fred-pe** [microsoft/idfix#39]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of IdFix you are using: [2.3.0]

I was using an old version of IDFix (1.09) so far, with the new version (2.3) I have a lot of errors because the targetAddress attribute is empty.
It seemed to me that in the case of a dedicated tenant that this attribute was not necessary if the homeMdb attribute was filled in.
Extract "not blank (contact and user without homeMdb)" from https://microsoft.github.io/idfix/supported-errors/#targetaddress_1

Thanks
Fred

**Comment by bryan-phillips-ms** [comment]
Fixed in version 2.6.0.0
