### ISSUE TITLE
mailnickname Duplicate

### ISSUE THREAD

**Issue by fred-pe** [microsoft/idfix#40]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of IdFix you are using: [2.3.0]

I have errors due to Duplicate mailnickname (they are indeed anomalies), but in the report there is only one of the 2 accounts indicated.
It would be more practical if the 2 accounts were indicated. It seems to me that the old version (1.09) did.

Thanks,
Fred

**Comment by teward** [comment]
This is confirmed in the latest version with an individual I've been working with.  Showing the two accounts is more practical than only showing one of the accounts.

**Comment by astavitsky** [comment]
Similar if not the same issue was reported as #29.  Not only it is not showing the second account/object, it is recommending to change the duplicate attribute to the SAME EXACT VALUE....  Please take a look at this issue.

**Comment by ITBlandMCT** [comment]
Same issue still a problem 2/19/2021

**Comment by bryan-phillips-ms** [comment]
Fixed in version 2.5.0.0
