### ISSUE TITLE
ChangeLog.md update needed for 2.3.0.0 release

### ISSUE THREAD

**Issue by SteveBurkettNZ** [microsoft/idfix#45]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version
2.3.0.0

### Expected / Desired Behavior / Question
An easy one: the CHANGELOG.md needs updating for the 2.3.0.0 release changes, only has up to 2.2.0.0 changes in there.

**Comment by bryan-phillips-ms** [comment]
Updated CHANGELOG.md to include details of 2.3.0.0 release
