### ISSUE TITLE
ID Fix Flagging Apostrophe as Invalid Character

### ISSUE THREAD

**Issue by nt4xp** [microsoft/idfix#46]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://microsoft.github.io/idfix/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

> If you are reporting a security related issue, instead of submitting it here, please email secure@microsoft.com to ensure it is properly handled to resolution.

### Category
- [ ] Enhancement
- [X ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [2.3.0.0         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

IDFix is flagging apostrophe as invalid character in UPN and ProxyAddresses; however,  apostrophe  is a valid character for syncing identities with AzureAD Connect.   No Sync Errors in AAD Connect when apostrophe is used. 

https://github.com/MicrosoftDocs/azure-docs/issues/14404

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making 
suggestion or asking a question delete this section.*
Expect IDFix to not flag UPN or ProxyAddress with apostrophe.

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

Sync and AD Object with UPN or Proxyaddresses to AzureAD that contain apostrophe. Observe no sync errors.

### Submission Guidelines

Thank you for your feedback!

**Comment by bryan-phillips-ms** [comment]
Fixed in version 2.6.0.0
