### ISSUE TITLE
Not considering other credentials

### ISSUE THREAD

**Issue by eliomex55** [microsoft/idfix#6]
### Expected Behavior
Use different credentials for specific forest at the moment of connection through settings panel.

### Observed Behavior
The credentials are not considered and Windows login session credentials are used neverminding if I chose Current credentials or Other credentials.

### Steps to Reproduce
Run IDFix to collect information from an Active Directory that doesn't accept your current windows login credentials.

Demonstrated using 389 protocol (LDAP plain text) and using wireshark the sent credentials are not correct and I receive Invalid credentials error.

**Comment by patrick-rodgers** [comment]
Thanks, will have a look.

**Comment by patrick-rodgers** [comment]
Yep, sure enough found the bug. Will be fixed in the next release, thanks for reporting it and letting us know!

**Comment by patrick-rodgers** [comment]
Just published a new version, 2.1.2.0 that should address this. Please let us know if that is not the case.
