### ISSUE TITLE
Schema Warning

### ISSUE THREAD

**Issue by mzatorskithi** [microsoft/idfix#63]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Observed Behavior
Schema Warning Notification Window upon clicking Query:

The following attributes are present in the schema but are not marked for replication to the Global Catalog and will not be analyzed for errors. Do you want to continue?
homeMdb
mailnickname

### Steps to Reproduce
Click Query

### Notes
These 2 attributes are in the schema and marked for replication but different letter case. 
- homeMdb in IdFix and homeMDB in Schema
- mailnickname in IdFix and mailNickname in Schema

**Comment by bryan-phillips-ms** [comment]
Fixed in version 2.6.0.0
