### ISSUE TITLE
Unable to query - Sequence contains no matching element

### ISSUE THREAD

**Issue by EdAzure** [microsoft/idfix#73]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version[ 2.6.0.1 and 2.5.0.0]

When I click on Query, instead of showing results, I get a message saying "Sequence contains no matching element". Below, it says "Error in RulesRunner: Sequence contains no matching element."

What could be wrong? I ran it on my server running AAD Connect, on a DC, and on my client system, I am getting the same results.

**Comment by EdAzure** [comment]
![idfix](https://user-images.githubusercontent.com/100852040/156581514-9c5dbab5-4c0d-495a-a6ce-ede7c865af75.JPG)

**Comment by bosco777** [comment]
We have the same issue.  We are able to run 1.11 without issue.

**Comment by dcwalker-500** [comment]
> We have the same issue. We are able to run 1.11 without issue.
we are having the issue as well with all of the versions listed 2.4.0 - 2.6.1, where were you able to get the 1.11 download?

**Comment by bosco777** [comment]
I just happened to still have it downloaded, but https://web.archive.org/web/20171112170519/https://www.microsoft.com/en-us/download/confirmation.aspx?id=36832 seems to work.  Might be able to try different dates until you get the newest one that still works for you to have as many updates as possible.

**Comment by arnetraedal** [comment]
We have this issue. 
A workaround can be to narrow the search using SearchBase parameter.
Querying the domain always fail.
