### ISSUE TITLE
Unsigned exe

### ISSUE THREAD

**Issue by ziggynemeth** [microsoft/idfix#9]
### Version
Please specify what version of IdFix you are using: [  1.11.6579.29793  ]

This executable from Microsoft is not signed. Please add this in the next version for authenticity and application whitelisting.

**Comment by patrick-rodgers** [comment]
The current releases should all be signed starting with 2.0. Can you please try installing the latest from the [readme here](https://raw.githubusercontent.com/Microsoft/idfix/master/publish/setup.exe)?

**Comment by patrick-rodgers** [comment]
Going to close this due to no feedback. Have confirmed that all of the exes we have published were signed. Can't speak to anything that happened before 2.*. Thanks!
